# Generated by Django 4.1 on 2024-02-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.TextField()),
                ("ip_address", models.TextField()),
                ("n_connections", models.IntegerField()),
                ("last_date_connected", models.DateField()),
            ],
        ),
    ]
