# Generated by Django 4.1 on 2024-02-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VAMapp", "0002_rename_project_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_date_connected",
            field=models.DateTimeField(),
        ),
    ]
